name: 打包01项目
on:
  workflow_dispatch:
    inputs:
      ad:
        description: '打包'
        required: true
        default: 'true'
        type: boolean
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 读取项目
        uses: actions/checkout@v4

      - name: 设置node版本
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 安装依赖
        run: |
          cd 01-quick-start
          npm install
          npm run build

      - name: 安装nw和nw-builder
        run:
          npm install -g nw nw-builder

      - name: 写入package.json
        run: |
          cd 01-dist
          Set-Content -Path package.json -Value '{ "name": "01-dist", "version": "1.0.0", "main": "index.html", "window": { "icon": "vite.svg" } }'

      - name: 查看目录
        run:  |
          cd 01-dist
          ls
          
        

      - name: 打包nw
        run: |
          cd 01-dist
          nwbuild --mode=build --glob=false --flavor=sdk --cacheDir=./node_modules/nw --outDir=../build ./

