name: 打包01项目
on:
  workflow_dispatch:
    inputs:
      ad:
        description: '打包'
        required: true
        default: 'true'
        type: boolean
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 读取项目
        uses: actions/checkout@v4

      - name: 设置node版本
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 缓存pnpm依赖
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: 安装pnpm并配置环境
        run: |
            npm install -g pnpm
            pnpm setup
          

      - name: 安装依赖
        run: |
          cd 01-quick-start
          pnpm install
          pnpm run build

      - name: 安装nw和nw-builder
        run:
          pnpm install -g nw nw-builder
        
      - name: 检查package.json, 有则删除
        run: |
          if [ -f package.json ]; then
            echo "package.json 已存在，跳过生成"
          else
            echo '{ "name": "01-dist", "version": "1.0.0", "main": "index.html", "window": { "icon": "vite.svg" } }' > package.json
          fi
      - name: 查看目录
        run:  pwd
      - name: 打包nw
        run: |
          cd 01-dist
          nwbuild --mode=build --glob=false --flavor=sdk --cacheDir=./node_modules/nw --outDir=../build ./

