name: 打包01项目
on:
  workflow_dispatch:
    inputs:
      ad:
        description: '打包'
        required: true
        default: 'true'
        type: boolean
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 读取项目
        uses: actions/checkout@v4

      - name: 设置node版本
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 安装依赖并第一次打包
        run: |
          cd 01-quick-start
          npm install
          npm run build

      - name: 第二次打包
        run: |
          cd 01-dist
          npm install
          npm run build
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
